//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.2.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using bielu.Umbraco.Cdn.Bunny.Net.CCU.Interface;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"

namespace bielu.Umbraco.Cdn.Bunny.Net.CCU.Service
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.2.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BunnyNetEdgeApiClient : IBunnyNetEdgeApiClient
    {
    #pragma warning disable 8618 // Set by constructor via BaseUrl property
        private string _baseUrl;
    #pragma warning restore 8618 // Set by constructor via BaseUrl property
        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings, true);

        public BunnyNetEdgeApiClient(System.Net.Http.HttpClient httpClient)
        {
            BaseUrl = "https://storage.bunnycdn.com/";
            _httpClient = httpClient;
        }

        private static Newtonsoft.Json.JsonSerializerSettings CreateSerializerSettings()
        {
            var settings = new Newtonsoft.Json.JsonSerializerSettings();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set
            {
                _baseUrl = value;
                if (!string.IsNullOrEmpty(_baseUrl) && !_baseUrl.EndsWith("/"))
                    _baseUrl += '/';
            }
        }

        protected Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettings { get { return _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <summary>
        /// Download File
        /// </summary>
        /// <remarks>
        /// Returns the stored file at the given path. If the file does not exist, a 404 response will be returned.
        /// </remarks>
        /// <param name="storageZoneName">The name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path to your file. If this is the root of your storage zone, you can ignore this parameter.</param>
        /// <param name="fileName">The name of the file that you wish to download.</param>
        /// <param name="accessKey">The API AccessKey used for authentication.</param>
        /// <returns>Returns the file stored at the given path.</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task AnonymousGETAsync(string storageZoneName, string path, string fileName, string accessKey)
        {
            return AnonymousGETAsync(storageZoneName, path, fileName, accessKey, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Download File
        /// </summary>
        /// <remarks>
        /// Returns the stored file at the given path. If the file does not exist, a 404 response will be returned.
        /// </remarks>
        /// <param name="storageZoneName">The name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path to your file. If this is the root of your storage zone, you can ignore this parameter.</param>
        /// <param name="fileName">The name of the file that you wish to download.</param>
        /// <param name="accessKey">The API AccessKey used for authentication.</param>
        /// <returns>Returns the file stored at the given path.</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task AnonymousGETAsync(string storageZoneName, string path, string fileName, string accessKey, System.Threading.CancellationToken cancellationToken)
        {
            if (storageZoneName == null)
                throw new System.ArgumentNullException("storageZoneName");

            if (path == null)
                throw new System.ArgumentNullException("path");

            if (fileName == null)
                throw new System.ArgumentNullException("fileName");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (accessKey == null)
                        throw new System.ArgumentNullException("accessKey");
                    request_.Headers.TryAddWithoutValidation("AccessKey", ConvertToString(accessKey, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("GET");

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(BaseUrl)) urlBuilder_.Append(BaseUrl);
                    // Operation Path: "{storageZoneName}/{path}/{fileName}"
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(storageZoneName, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(path, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(fileName, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<ErrorObject>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new BunnyNetEdgeApiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new BunnyNetEdgeApiApiException<System.Collections.Generic.ICollection<ErrorObject>>("The file on the given path does not exist.", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new BunnyNetEdgeApiApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Upload File
        /// </summary>
        /// <remarks>
        /// Upload a file to a storage zone based on the URL path. If the directory tree does not exist, it will be created automatically. **The file content should be sent as the body of the request without any type of encoding.**
        /// </remarks>
        /// <param name="body">Raw request body should contain the contents of the file. This should be raw file data without any sort of encoding.</param>
        /// <param name="storageZoneName">he name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path to where your file will be stored. If this is the root of your storage zone, you can ignore this parameter.</param>
        /// <param name="fileName">The name that the file will be uploaded as.</param>
        /// <param name="checksum">The SHA256 checksum of the uploaded content. The server will compare the final SHA256 to the checksum and reject the request in case the checksums do not match.</param>
        /// <param name="accessKey">The API AccessKey used for authentication.</param>
        /// <returns>The file upload was successful.</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task AnonymousPUTAsync(System.IO.Stream body, string storageZoneName, string path, string fileName, string checksum, string accessKey)
        {
            return AnonymousPUTAsync(body, storageZoneName, path, fileName, checksum, accessKey, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Upload File
        /// </summary>
        /// <remarks>
        /// Upload a file to a storage zone based on the URL path. If the directory tree does not exist, it will be created automatically. **The file content should be sent as the body of the request without any type of encoding.**
        /// </remarks>
        /// <param name="body">Raw request body should contain the contents of the file. This should be raw file data without any sort of encoding.</param>
        /// <param name="storageZoneName">he name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path to where your file will be stored. If this is the root of your storage zone, you can ignore this parameter.</param>
        /// <param name="fileName">The name that the file will be uploaded as.</param>
        /// <param name="checksum">The SHA256 checksum of the uploaded content. The server will compare the final SHA256 to the checksum and reject the request in case the checksums do not match.</param>
        /// <param name="accessKey">The API AccessKey used for authentication.</param>
        /// <returns>The file upload was successful.</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task AnonymousPUTAsync(System.IO.Stream body, string storageZoneName, string path, string fileName, string checksum, string accessKey, System.Threading.CancellationToken cancellationToken)
        {
            if (storageZoneName == null)
                throw new System.ArgumentNullException("storageZoneName");

            if (path == null)
                throw new System.ArgumentNullException("path");

            if (fileName == null)
                throw new System.ArgumentNullException("fileName");

            if (body == null)
                throw new System.ArgumentNullException("body");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (checksum != null)
                        request_.Headers.TryAddWithoutValidation("Checksum", ConvertToString(checksum, System.Globalization.CultureInfo.InvariantCulture));

                    if (accessKey == null)
                        throw new System.ArgumentNullException("accessKey");
                    request_.Headers.TryAddWithoutValidation("AccessKey", ConvertToString(accessKey, System.Globalization.CultureInfo.InvariantCulture));
                    var content_ = new System.Net.Http.StreamContent(body);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/octet-stream");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("PUT");

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(BaseUrl)) urlBuilder_.Append(BaseUrl);
                    // Operation Path: "{storageZoneName}/{path}/{fileName}"
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(storageZoneName, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(path, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(fileName, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 201)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new BunnyNetEdgeApiApiException("Upload failed.", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new BunnyNetEdgeApiApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Delete File
        /// </summary>
        /// <remarks>
        /// Delete an object from the storage zone. In case the object is a directory all the data in it will be recursively deleted as well.
        /// </remarks>
        /// <param name="storageZoneName">The name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path to your file. If this is the root of your storage zone, you can ignore this parameter.</param>
        /// <param name="fileName">The name of the file that you wish to delete.</param>
        /// <param name="accessKey">The API AccessKey used for authentication.</param>
        /// <returns>Object was successfully deleted</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task AnonymousDELETEAsync(string storageZoneName, string path, string fileName, string accessKey)
        {
            return AnonymousDELETEAsync(storageZoneName, path, fileName, accessKey, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Delete File
        /// </summary>
        /// <remarks>
        /// Delete an object from the storage zone. In case the object is a directory all the data in it will be recursively deleted as well.
        /// </remarks>
        /// <param name="storageZoneName">The name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path to your file. If this is the root of your storage zone, you can ignore this parameter.</param>
        /// <param name="fileName">The name of the file that you wish to delete.</param>
        /// <param name="accessKey">The API AccessKey used for authentication.</param>
        /// <returns>Object was successfully deleted</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task AnonymousDELETEAsync(string storageZoneName, string path, string fileName, string accessKey, System.Threading.CancellationToken cancellationToken)
        {
            if (storageZoneName == null)
                throw new System.ArgumentNullException("storageZoneName");

            if (path == null)
                throw new System.ArgumentNullException("path");

            if (fileName == null)
                throw new System.ArgumentNullException("fileName");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (accessKey == null)
                        throw new System.ArgumentNullException("accessKey");
                    request_.Headers.TryAddWithoutValidation("AccessKey", ConvertToString(accessKey, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("DELETE");

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(BaseUrl)) urlBuilder_.Append(BaseUrl);
                    // Operation Path: "{storageZoneName}/{path}/{fileName}"
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(storageZoneName, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(path, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(fileName, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new BunnyNetEdgeApiApiException("Object delete failed", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new BunnyNetEdgeApiApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// List Files
        /// </summary>
        /// <remarks>
        /// Retrieve a list of files and directories located in the given directory.
        /// </remarks>
        /// <param name="storageZoneName">he name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path that you want to list.</param>
        /// <returns>A JSON encoded array of objects.</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<StorageObject>> AnonymousAllAsync(string storageZoneName, string path)
        {
            return AnonymousAllAsync(storageZoneName, path, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List Files
        /// </summary>
        /// <remarks>
        /// Retrieve a list of files and directories located in the given directory.
        /// </remarks>
        /// <param name="storageZoneName">he name of your storage zone where you are connecting to.</param>
        /// <param name="path">The directory path that you want to list.</param>
        /// <returns>A JSON encoded array of objects.</returns>
        /// <exception cref="BunnyNetEdgeApiApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<StorageObject>> AnonymousAllAsync(string storageZoneName, string path, System.Threading.CancellationToken cancellationToken)
        {
            if (storageZoneName == null)
                throw new System.ArgumentNullException("storageZoneName");

            if (path == null)
                throw new System.ArgumentNullException("path");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("*/*"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(BaseUrl)) urlBuilder_.Append(BaseUrl);
                    // Operation Path: "{storageZoneName}/{path}/"
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(storageZoneName, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(path, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<StorageObject>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new BunnyNetEdgeApiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new BunnyNetEdgeApiApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                try
                {
                    var typedBody = Newtonsoft.Json.JsonConvert.DeserializeObject<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new BunnyNetEdgeApiApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
                    using (var streamReader = new System.IO.StreamReader(responseStream))
                    using (var jsonTextReader = new Newtonsoft.Json.JsonTextReader(streamReader))
                    {
                        var serializer = Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings);
                        var typedBody = serializer.Deserialize<T>(jsonTextReader);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new BunnyNetEdgeApiApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) 
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value is string[])
            {
                return string.Join(",", (string[])value);
            }
            else if (value.GetType().IsArray)
            {
                var valueArray = (System.Array)value;
                var valueTextArray = new string[valueArray.Length];
                for (var i = 0; i < valueArray.Length; i++)
                {
                    valueTextArray[i] = ConvertToString(valueArray.GetValue(i), cultureInfo);
                }
                return string.Join(",", valueTextArray);
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625